### ISSUE TITLE
set up instructions

### ISSUE THREAD

**Issue by andrewMacmurray** [kasaromi/package.sam#38]
would be useful to have set up instructions in the readme (like what to put in the config.env)

**Comment by Jbarget** [comment]
when you say to 'git clone' a reminder to 'cd' into the folder would be good. Make it idiot proof init

**Comment by hdrdavies** [comment]
You're not still doing that are you @Jbarget ? You could use some command line aliases to stop that from happening?

**Comment by Jbarget** [comment]
im talking about all the peeps without the aliases or the idiots @hdrdavies :)

**Comment by RobStallion** [comment]
@andrewMacmurray @Jbarget  Cheers for the feedback. We've added that to the readme now

**Comment by Jbarget** [comment]
:+1:

**Comment by andrewMacmurray** [comment]
:+1:
